### ISSUE TITLE
身バレ大草原

### ISSUE THREAD

**Issue by venezsia1573** [SaltfishAmi/get-the-fuck-out-of-shanghai#1]
お久しぶり。
完全にシナ語話者になってるようですね。
しかも顔写真添付なんて一秒でも早くムショに入りたいっていうことですか。
引き続きこの調子で頑張ってくれ！
応援してますから(笑

**Comment by SaltfishAmi** [comment]
元々このアカウントでは正体を隠せているなんて思っておらぬ
